import { createHash } from "node:crypto";
import type { HyperFrameAspectRatio, HyperFrameCompositionRequest, HyperFrameCompositionResult } from "@/lib/hyperframes/types";
const MAX_CAPTION_LENGTH = 500;
const MIN_DURATION_SECONDS = 3;
const MAX_DURATION_SECONDS = 60;
const aspectRatioMap: Record<HyperFrameAspectRatio, { width: number; height: number }> = { "16:9": { width: 1280, height: 720 }, "9:16": { width: 720, height: 1280 }, "1:1": { width: 1080, height: 1080 } };
export function escapeHtml(input: string): string { return input.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char] ?? char)); }
export function sanitizeCaptionText(input: string): string { return escapeHtml(input.replace(/<\s*\/\s*script\s*>/gi, "").replace(/<\s*script[^>]*>/gi, "").trim()).slice(0, MAX_CAPTION_LENGTH); }
export function validateMediaUrl(url?: string | null): string | null { if (!url) return null; try { const parsed = new URL(url); return ["https:", "http:"].includes(parsed.protocol) ? parsed.toString() : null; } catch { return null; } }
export function clampDuration(durationSeconds: number): number { return Math.max(MIN_DURATION_SECONDS, Math.min(MAX_DURATION_SECONDS, durationSeconds)); }
export function buildHyperFrameComposition(input: HyperFrameCompositionRequest & { product: { title: string; price: string; currency: string; imageUrl?: string | null; affiliateUrl?: string | null } }): HyperFrameCompositionResult {
  const { width, height } = aspectRatioMap[input.aspectRatio]; const caption = sanitizeCaptionText(input.caption); const safeTitle = escapeHtml(input.product.title); const safePrice = escapeHtml(`${input.product.price} ${input.product.currency}`); const safeImage = validateMediaUrl(input.product.imageUrl); const hasAffiliate = Boolean(input.product.affiliateUrl); const safeDisclosure = hasAffiliate ? "*โพสต์นี้อาจมีลิงก์แอฟฟิลิเอต ผู้เขียนอาจได้รับค่าคอมมิชชัน*" : ""; const duration = clampDuration(input.durationSeconds);
  const compositionId = createHash("sha256").update(JSON.stringify({ input: { ...input, caption, duration }, width, height })).digest("hex").slice(0, 16);
  const compositionHtml = `<!doctype html><html lang="th"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><style>body{margin:0;background:#0f172a;color:#fff;font-family:system-ui,sans-serif}.stage{position:relative;overflow:hidden;width:${width}px;height:${height}px;background:linear-gradient(135deg,#0f172a,#1e293b)}.media{position:absolute;inset:0;opacity:.85;object-fit:cover;width:100%;height:100%}.overlay{position:absolute;inset:0;background:linear-gradient(180deg,transparent 20%,rgba(0,0,0,.65) 100%)}.caption{position:absolute;left:36px;right:36px;bottom:180px;font-size:42px;font-weight:700;line-height:1.2;animation:fadeUp .8s ease both}.meta{position:absolute;left:36px;right:36px;bottom:88px;display:flex;justify-content:space-between;align-items:center}.cta{background:#22c55e;color:#052e16;padding:14px 18px;border-radius:999px;font-weight:700}.disclosure{position:absolute;left:36px;right:36px;bottom:20px;font-size:20px;opacity:.9}@keyframes fadeUp{from{transform:translateY(18px);opacity:0}to{transform:none;opacity:1}}</style></head><body><div class="stage" data-composition-id="${compositionId}" data-start="0" data-width="${width}" data-height="${height}" data-duration="${duration}">${safeImage ? `<img class="media" src="${safeImage}" alt="${safeTitle}" />` : ""}<div class="overlay"></div><div class="caption">${caption || safeTitle}</div><div class="meta"><div>${safeTitle}<br/>${safePrice}</div><div class="cta">ซื้อผ่านลิงก์แนะนำ</div></div>${safeDisclosure ? `<div class="disclosure">${escapeHtml(safeDisclosure)}</div>` : ""}</div></body></html>`;
  return { compositionId, compositionHtml, metadata: { productId: input.productId, productTitle: input.product.title, platform: input.platform, aspectRatio: input.aspectRatio, durationSeconds: duration, width, height, hasAffiliateDisclosure: hasAffiliate } };
}
