// server-only marqeta core api wrapper
import { loadMarqetaConfig } from "@/lib/marqeta/config";
export type MarqetaApiError = { code: string; status: number; message: string; retryable: boolean };
type Method = "GET" | "POST" | "PUT";
const transientStatuses = new Set([429, 500, 502, 503, 504]);
const redact = (text: string): string => text.replace(/authorization\s*:[^,\n]*/gi, "authorization:[REDACTED]").replace(/(token|secret|password)\s*[:=]\s*[^\s,]*/gi, "$1:[REDACTED]");
export class MarqetaCoreApiService { constructor(private readonly fetchImpl: typeof fetch = fetch, private readonly sleep: (ms: number) => Promise<void> = (ms) => new Promise((r) => setTimeout(r, ms))) {}
  private authHeader(): string { const cfg = loadMarqetaConfig(); return `Basic ${Buffer.from(`${cfg.applicationToken ?? ""}:${cfg.adminAccessToken ?? ""}`).toString("base64")}`; }
  async request<T>(input: { method: Method; path: string; body?: unknown; idempotencyKey?: string; safeToRetry?: boolean }): Promise<T> { const cfg = loadMarqetaConfig(); const canRetry = input.method === "GET" || input.safeToRetry === true; if ((input.method === "POST" || input.method === "PUT") && input.safeToRetry && !input.idempotencyKey) throw <MarqetaApiError>{ code: "IDEMPOTENCY_KEY_REQUIRED", status: 400, message: "Idempotency key is required for retried mutating calls", retryable: false }; let attempt = 0; while (true) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), cfg.timeoutMs); try { const res = await this.fetchImpl(`${cfg.baseUrl}${input.path}`, { method: input.method, headers: { Authorization: this.authHeader(), ...(input.method !== "GET" ? { "Content-Type": "application/json" } : {}), ...(input.idempotencyKey ? { "Idempotency-Key": input.idempotencyKey } : {}) }, body: input.body ? JSON.stringify(input.body) : undefined, signal: controller.signal }); clearTimeout(timeout); const json = await res.json().catch(() => ({})); if (res.ok) return json as T; const shaped: MarqetaApiError = { code: `MARQETA_HTTP_${res.status}`, status: res.status, message: redact(typeof (json as { error_message?: unknown }).error_message === "string" ? (json as { error_message: string }).error_message : `Marqeta error ${res.status}`), retryable: transientStatuses.has(res.status) }; if (attempt < cfg.maxRetries && canRetry && shaped.retryable) { attempt += 1; await this.sleep(100 * 2 ** attempt); continue; } throw shaped; } catch (error) { clearTimeout(timeout); if ((error as { name?: string }).name === "AbortError") throw <MarqetaApiError>{ code: "MARQETA_TIMEOUT", status: 504, message: "Marqeta request timed out", retryable: true }; if ((error as MarqetaApiError).code) throw error; throw <MarqetaApiError>{ code: "MARQETA_CLIENT_ERROR", status: 502, message: redact(error instanceof Error ? error.message : "Unknown Marqeta client error"), retryable: false }; } } }
  async connectivityCheck(): Promise<{ ok: boolean; status: number | null }> { try { await this.request({ method: "GET", path: "/ping", safeToRetry: true }); return { ok: true, status: 200 }; } catch (error) { const err = error as MarqetaApiError; return { ok: false, status: typeof err.status === "number" ? err.status : null }; } }
}
